# Generated by Django 5.0.4 on 2024-11-14 19:39

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=20, verbose_name='نام مدل')),
                ('persian_model_name', models.CharField(max_length=20, verbose_name='نام فارسی مدل')),
                ('fields_data', models.TextField(blank=True, null=True, verbose_name='اطلاعات فیلدها')),
                ('created_time', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_time', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
            ],
            options={
                'verbose_name': 'اطلاعات فیلدهای مدل',
                'verbose_name_plural': 'اطلاعات فیلدهای مدل\u200cها',
            },
        ),
        migrations.CreateModel(
            name='ProvinceCountyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_name', models.CharField(max_length=30, verbose_name='نام استان')),
                ('province_slug', models.SlugField(verbose_name='نام آدرس استان')),
                ('county_list', models.TextField(blank=True, null=True, verbose_name='لیست شهرستان\u200cها')),
                ('created_time', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_time', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
            ],
            options={
                'verbose_name': 'لیست شهرستان\u200cهای استان',
                'verbose_name_plural': 'لیست شهرستان\u200cهای استان\u200cها',
            },
        ),
    ]
