# Generated by Django 5.0.4 on 2024-11-29 10:51

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن ثابت')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='موبایل')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('descriptions', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('national_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد ملی')),
                ('ownership_type', models.CharField(blank=True, choices=[('real', 'حقیقی'), ('legal', 'حقوقی')], max_length=5, null=True, verbose_name='نوع مالکیت')),
                ('created_time', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_time', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
            ],
            options={
                'verbose_name': 'مالک',
                'verbose_name_plural': 'مالکین',
            },
        ),
    ]
